name: Backport
'on':
  pull_request_target:
    types:
    - closed
    - labeled
    branches:
    - master
    - release/*
permissions:
  contents: write
  pull-requests: write
jobs:
  backport:
    name: Backport Pull Request
    if: github.repository_owner == 'cidsod7z' && github.event.pull_request.merged
      == true && (github.event_name != 'labeled' || startsWith('backport', github.event.label.name))
    runs-on: ubuntu-latest
    environment: github-write
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        token: ${{ secrets.CRYSBOT_WRITE_PAT }}
        persist-credentials: false
    - name: Create backport PR
      uses: korthout/backport-action@3c06f323a58619da1e8522229ebc8d5de2633e46
      with:
        github_token: ${{ secrets.CRYSBOT_WRITE_PAT }}
        copy_labels_pattern: ^(breaking-change|security|topic:.*|kind:.*|platform:.*)$
        copy_milestone: true
        pull_description: 'Automated backport of #${pull_number} to `${target_branch}`,
          triggered by a label.'
